name: p2p_file_sharing
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  flutter_to_debian: ^2.0.2
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons:

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
